apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v3.0
        args:
          - --global.checknewversion
          - --entryPoints.main.address=:9000/tcp
          - --entryPoints.metrics.address=:9180/tcp
          - --entryPoints.web.address=:80/tcp
          - --entryPoints.websecure.address=:443/tcp
          - --api.dashboard=true
          - --ping=true
          - --metrics.prometheus=true
          - --metrics.prometheus.entrypoint=metrics
          - --providers.kubernetescrd
          - --providers.kubernetesingress
          - --providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik-tcp
          - --entrypoints.web.http.redirections.entryPoint.to=:443
          - --entrypoints.web.http.redirections.entryPoint.scheme=https
          - --entrypoints.websecure.http.tls=true
          - --log.format=common
          - --serverstransport.insecureskipverify=true
          - --providers.kubernetesingress.allowexternalnameservices=true
        ports:
          - containerPort: 9000
            name: main
            protocol: TCP
          - containerPort: 9180
            name: metrics
            protocol: TCP
          - containerPort: 80
            name: web
            protocol: TCP
          - containerPort: 443
            name: websecure
            protocol: TCP
        env:
          - name: TZ
            value: "America/Chicago"
          - name: UMASK
            value: "0022"
          - name: UMASK_SET
            value: "0022"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 568
          runAsNonRoot: true
          runAsUser: 568
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
