apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusOperator
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  logLevel: 'info'

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  retention: 31d
  retentionSize: "2GB"
  scrapeInterval: 15s
  evaluationInterval: 30s
  disableCompaction: false
  walCompression: false
  enableAdminAPI: false
  logLevel: 'info'
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  ruleSelector: {}
  ruleNamespaceSelector: {}
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: web


---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  logLevel: 'info'

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  logLevel: 'info'


---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  logLevel: 'info'


---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  logLevel: 'info'
  retention: 240h

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.101.70
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.101.71
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: main

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
spec:
  rules:
  - host: prometheus.techcasa.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              name: web
