mappings:

################################################
# Proxmox Storages
################################################

- match: 'proxmox\.storages\.(.*)\.(.*)\.(.*)'
  match_type: regex
  name: 'proxmox_storage_nodes_${3}'
  labels:
    job: proxmox
    node: ${1}
    storage: ${2}
    metric: ${3}


################################################
# Proxmox VM
################################################

- match: 'proxmox\.(lxc|qemu)\.(.*)\.blockstat\.(.*)'
  match_type: regex
  name: 'proxmox_vm_blockstat'
  labels:
    job: proxmox
    vmid: ${1}
    metric: ${2}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.nics\.(.*)\.netin'
  match_type: regex
  name: 'proxmox_vm_nics_netin'
  labels:
    job: proxmox
    vmid: ${1}
    nic: ${2}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.nics\.(.*)\.netout'
  match_type: regex
  name: 'proxmox_vm_nics_netout'
  labels:
    job: proxmox
    vmid: ${1}
    nic: ${2}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.cpu'
  match_type: regex
  name: 'proxmox_vm_cpu'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.cpus'
  match_type: regex
  name: 'proxmox_vm_cpu'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.disk'
  match_type: regex
  name: 'proxmox_vm_disk'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.diskread'
  match_type: regex
  name: 'proxmox_vm_diskread'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.diskwrite'
  match_type: regex
  name: 'proxmox_vm_diskwrite'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.maxdisk'
  match_type: regex
  name: 'proxmox_vm_maxdisk'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.maxmem'
  match_type: regex
  name: 'proxmox_vm_maxmem'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.maxswap'
  match_type: regex
  name: 'proxmox_vm_maxswap'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.mem'
  match_type: regex
  name: 'proxmox_vm_mem'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.netin'
  match_type: regex
  name: 'proxmox_vm_netin'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.netout'
  match_type: regex
  name: 'proxmox_vm_netout'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.swap'
  match_type: regex
  name: 'proxmox_vm_swap'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.uptime'
  match_type: regex
  name: 'proxmox_vm_uptime'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.vmid'
  match_type: regex
  name: 'proxmox_vm_vmid'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.actual'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_actual'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.free.mem'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_free_mem'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.last.update'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_last_update'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.major.page.faults'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_major_page_faults'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.max.mem'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_max_mem'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.mem.swapped.in'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_mem_swapped_in'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.mem.swapped.out'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_mem_swapped_out'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.minor.page.faults'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_minor_page_faults'
  labels:
    job: proxmox
    vmid: ${1}

- match: 'proxmox\.(lxc|qemu)\.(.*)\.ballooninfo.total.mem'
  match_type: regex
  name: 'proxmox_vm_ballooninfo_total_mem'
  labels:
    job: proxmox
    vmid: ${1}


################################################
# Proxmox Nodes
################################################

- match: proxmox.node.*.uptime
  name: 'proxmox_node_uptime'
  labels:
    job: proxmox
    node: ${1}

- match: proxmox.node.*.nics.*.*
  name: 'proxmox_node_nic_${3}'
  labels:
    job: proxmox
    node: ${1}
    nic: ${2}
    transceive: ${3}

# - match: proxmox.node.*.blockstat.*
#   name: 'proxmox_node_blockstat_${2}
#   labels:
#     job: proxmox
#     node: ${1}
#     kind: ${2}

# - match: proxmox.node.*.cpustat.*
#   name: 'proxmox_node_cpustat
#   labels:
#     job: proxmox
#     node: ${1}
#     kind: ${2}

# - match: proxmox.node.*.memory.*
#   name: 'proxmox_node_memory
#   labels:
#     job: proxmox
#     node: ${1}
#     kind: ${2}

