apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`grafana.techcasa.io`) && Path(`/login`)
    services:
    - name: grafana
      namespace: monitoring
      port: 3000
