apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: "${ACME_EMAIL}"
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: api-token
    # - http01:
    #     ingress:
    #       class: traefik-external
