name: monitoring

########################### NETWORKS
# You may customize the network subnets (10.10.x.0/24) below as you please.

networks:
  monitoring-services:
    name: monitoring-services
    driver: bridge

x-common: &common
  restart: unless-stopped
  networks:
    - monitoring-services
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"
      loki-external-labels: "container_name={{.Name}}"
  labels:
    org.label-schema.group: "monitoring"

########################### SECRETS

########################### INCLUDE

include:
  - monitoring/alertmanager.yml
  - monitoring/cadvisor.yml
  - monitoring/grafana.yml
  - monitoring/graphite-exporter-proxmox.yml
  - monitoring/graphite-exporter-truenas.yml
  - monitoring/loki.yml
  - monitoring/prometheus.yml
  - monitoring/promtail.yml
  - monitoring/pushgateway.yml
  - monitoring/renderer.yml
  # - monitoring/tdarr-exporter.yml
  - monitoring/unpoller.yml
