[[roles]]
name = "test"
# Define a list of routes with the syntax "Http-Method /path"
# routes = ["GET /v1/openvpn/portforwarded"]
# Define an authentication method with its parameters
auth = "none"
username = "admin"
password = "password123"
