# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 10s
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'homelab'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: 'cadvisor'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.10.100.190:9100']
        labels:
          alias: 'node-exporter'

  - job_name: 'graphite-exporter'
    static_configs:
      - targets: ['graphite-exporter:9108']
        labels:
          alias: 'graphite-exporter'

# Internal port for the graphite-exporter
  - job_name: 'graphite-exporter2'
    static_configs:
      - targets: ['graphite-exporter2:9108']
        labels:
          alias: 'graphite-exporter2'

  - job_name: 'unifipoller'
    static_configs:
      - targets: ['unpoller:9130']
        labels:
          alias: 'unifipoller'