---
name: <your project name>
services:
    graphite-statsd:
        image: graphiteapp/graphite-statsd
        container_name: graphite
        volumes:
            - $(pwd)/graphite/conf:/opt/graphite/conf
            - $(pwd)/graphite/storage:/opt/graphite/storage
        ports:
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 9080:80
        restart: always