services:
  renderer:
    image: grafana/grafana-image-renderer:${RENDERER_TAG:-3.11.0}
    container_name: grafana-image-renderer
    ports:
      - "8081:8081"
    environment:
      - ENABLE_METRICS=false
    restart: unless-stopped
    networks:
      - monitoring-services
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}}"
    labels:
      org.label-schema.group: "monitoring"