services:
  unpoller:
    image: ghcr.io/unpoller/unpoller:${UP_POLLER_TAG:-latest}
    container_name: unpoller
    environment:
      - UP_INFLUXDB_DISABLE=${UP_INFLUXDB_DISABLE:-true}
      - UP_LOKI_URL=${UP_LOKI_URL:-http://loki:3100}
      - UP_UNIFI_DYNAMIC=${UP_UNIFI_DYNAMIC:-false}
      - UP_UNIFI_DEFAULT_USER=${UP_UNIFI_USER:-admin}
      - UP_UNIFI_DEFAULT_PASS=${UP_UNIFI_PASS:-password123}
      - UP_UNIFI_DEFAULT_URL=${UP_UNIFI_URL:-https://unifi:8443}
      - UP_UNIFI_DEFAULT_SAVE_ALARMS=${UP_UNIFI_SAVE_ALARMS:-true}
      - UP_UNIFI_DEFAULT_SAVE_ANOMALIES=${UP_UNIFI_SAVE_ANOMALIES:-true}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${UP_UNIFI_SAVE_DPI:-true}
      - UP_UNIFI_DEFAULT_SAVE_EVENTS=${UP_UNIFI_SAVE_EVENTS:-true}
      - UP_UNIFI_DEFAULT_SAVE_SITES=${UP_UNIFI_SAVE_SITES:-true}
      - UP_POLLER_DEBUG=${UP_POLLER_DEBUG:-false}
      - UP_POLLER_QUIET=${UP_POLLER_QUIET:-true}
      - UP_PROMETHEUS_DISABLE=${UP_PROMETHEUS_DISABLE:-false}
      - UP_PROMETHEUS_NAMESPACE=${UP_PROMETHEUS_NAMESPACE:-unpoller}
      - UP_PROMETHEUS_HTTP_LISTEN=${UP_PROMETHEUS_HTTP_LISTEN:-0.0.0.0:9130}
      - UP_PROMETHEUS_REPORT_ERRORS=${UP_PROMETHEUS_REPORT_ERRORS:-false}
      - UP_PROMETHEUS_BUFFER=${UP_PROMETHEUS_BUFFER:-50}
    restart: unless-stopped
    networks:
      - monitoring-services
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}}"
    labels:
      org.label-schema.group: "monitoring"