---
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config_data:/config
      - downloads_data:/downloads
      - /mnt/family_sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped

volumes:
  config_data:
    external: false
    name: config_data
  downloads_data:
    external: false
    name: downloads_data