---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: ${CLOUDFLARE_API_TOKEN}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certificateissuer
  namespace: cert-manager
spec:
  acme:
    email: ryanwclark@yahoo.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - dns01:
        cloudflare:
          email: ryanwclark@yahoo.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: cert-manager
spec:
  secretName: techcasa-tls
  issuerRef:
    name: certificateissuer
    kind: ClusterIssuer
  dnsNames:
  - '*.techcasa.io'
  - 'techcasa.io'