services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:${ATUIN_TAG:-v18.3.0}
    command: server start
    volumes:
      - config-data:/config
    links:
      - postgresql:db
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: ${ATUIN_HOST:-0.0.0.0}
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
  postgresql:
    image: postgres:16
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
  backup:
    container_name: atuin_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_DB: ${ATUIN_DB_NAME}
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
    volumes:
      - pgdumps:/db_dumps
    depends_on:
      - postgresql
volumes:
  pgdata:
    driver: local
  pgdumps:
    driver: local
  config-data:
    driver: local