services:
  tailscale:
    image: tailscale/tailscale:latest #{$TAILSCALE_TAG:-latest}
    hostname: tailscale
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=atuin
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - tailscale-nginx
  #   network_mode: service:tailscale-nginx

  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:${ATUIN_TAG:-v18.3.0}
    command: server start
    volumes:
      - atuin-config-data:/config
    links:
      - postgresql:db
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: ${ATUIN_HOST:-0.0.0.0}
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
  postgresql:
    image: postgres:16
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
  backup:
    container_name: atuin_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_DB: ${ATUIN_DB_NAME}
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
    volumes:
      - pgdumps:/db_dumps
    depends_on:
      - postgresql
volumes:
  pgdata:
    driver: local
  pgdumps:
    driver: local
  atuin-config-data:
    driver: local
  tailscale-data:
    driver: local