services:
  tailscale:
    image: tailscale/tailscale:${TAILSCALE_TAG:-latest}
    hostname: tailscale
    privileged: true
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=atuin
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    network_mode: host

  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:${ATUIN_TAG:-latest}
    container_name: atuin
    command: server start
    volumes:
      - atuin-config-data:/config
    links:
      - postgres:db

    ports:
      - mode: ingress
        target: 8888
        published: 8888
        protocol: tcp
    environment:
      ATUIN_HOST: ${ATUIN_HOST:-0.0.0.0}
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME:-atuin}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD:-password123}
      POSTGRES_DB: ${ATUIN_DB_NAME:-atuin}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${ATUIN_DB_NAME}"]
      start_period: 20s
      interval: 10s

  backup:
    image: prodrigestivill/postgres-backup-local:latest
    container_name: db-backup
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${ATUIN_DB_USERNAME:-atuin}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD:-password123}
      POSTGRES_DB: ${ATUIN_DB_NAME:-atuin}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
    volumes:
      - pgdumps:/db_dumps
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
  pgdumps:
    driver: local
  atuin-config-data:
    driver: local
  tailscale-data:
    driver: local