services:
  # Client for Notifiarr.com
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media","arrs", "all"]
    networks:
      - arr_net
      # arr_net:
      #   ipv4_address: ${MEDIA_SERVER_IP:-10.10.100.50} # You can specify a static IP
    ports:
      - "5454:5454"
    volumes:
      - ${COMMON_CONFIG_PATH}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      DN_API_KEY: $NOTIFIARR_API_KEY
      DN_AUTO_UPDATE: off
      DN_BIND_ADDR: 0.0.0.0:5454
      DN_QUIET: false
      # DN_UI_PASSWORD: $NOTIFIARR_UI_PASSWORD
      DN_LIDARR_0_NAME: lidarr
      DN_LIDARR_0_URL: http://lidarr:8686
      DN_LIDARR_0_API_KEY: $LIDARR_API_KEY
      DN_PROWLARR_0_NAME: prowlarr
      DN_PROWLARR_0_URL: http://prowlarr:9696
      DN_PROWLARR_0_API_KEY: $PROWLARR_API_KEY
      DN_RADARR_0_NAME: radarr
      DN_RADARR_0_URL: http://radarr:7878
      DN_RADARR_0_API_KEY: $RADARR_API_KEY
      DN_READARR_0_NAME: readarr
      DN_READARR_0_URL: http://readarr:8787
      DN_READARR_0_API_KEY: $READARR_API_KEY
      DN_SONARR_0_NAME: sonarr
      DN_SONARR_0_URL: http://sonarr:8989
      DN_SONARR_0_API_KEY: $SONARR_API_KEY
      DN_QBIT_0_NAME: qbittorrent
      DN_QBIT_0_URL: http://gluetun:8089
      DN_QBIT_0_USER: $QBITTORRENT_USER
      DN_QBIT_0_PASS: $QBITTORRENT_PASSWORD






    # labels:
      # - "traefik.enable=true"
      # # HTTP Routers Auth
      # - "traefik.http.routers.notifiarr-rtr.entrypoints=websecure"
      # - "traefik.http.routers.notifiarr-rtr.rule=Host(`notifiarr.$DOMAINNAME`)"
      # # Middlewares
      # # - "traefik.http.routers.notifiarr-rtr.middlewares=chain-oauth@file"
      # # HTTP Services
      # - "traefik.http.routers.notifiarr-rtr.service=notifiarr-svc"
      # - "traefik.http.services.notifiarr-svc.loadbalancer.server.port=5454"