apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techcasa-io-production
  namespace: cert-manager
spec:
  secretName: techcasa-io-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.techcasa.io'
  dnsNames:
  - '*.techcasa.io'
