apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techcasa-io-staging
  namespace: cert-manager
spec:
  secretName: techcasa-io-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.techcasa.io'
  dnsNames:
  - '*.techcasa.io'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"


