---
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - resillio_config_data:/config
      - downloads_data:/downloads
      - /mnt/family_sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped

volumes:
  resillio_config_data:
    external: false
    name: resillio_config_data
  downloads_data:
    external: false
    name: downloads_data
