---
name: influxdb
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE:-setup}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-BUCKET_NAME}
  telegraf:
    image: docker.io/telegraf:latest
    container_name: telegraf
    ports: # Is port needed for listener?
      - 8089:8089/udp
    # command: --config /telegraf_conf
    # configs:
    #   - telegraf_conf
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN:-password123}
    volumes:
      - type: bind
        source: ./telegraf/telegraf.conf
        target: /etc/telegraf/telegraf.conf
# configs:
#   telegraf_conf:
#     file: ./telegraf/telegraf.conf
volumes:
  influxdb2-data:
    external: true
    name: influxdb2-data
  influxdb2-config:
    external: true
    name: influxdb2-config