---
name: influxdb2
services:
    influxdb:
        image: influxdb:2
        container_name: influxdb2
        ports:
            - 8086:8086
        volumes:
            # - type: volume
              # source: influxdb2-data
            - type: bind
              source: /mnt/apps/influxdb
              target: /var/lib/influxdb2
            - type: bind
              source: /mnt/conf/influxdb
              target: /etc/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE:-setup}
            - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-ADMIN_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-ADMIN_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-ORG_NAME}
            - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-BUCKET_NAME}
# volumes:
#     influxdb2-data:
#         external: true
#         name: influxdb2-data
