global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 10s
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'homelab'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: 'cadvisor'

  # - job_name: 'lidarr'
  #   static_configs:
  #     - targets: ['lidarr-exporter:9709']
  #       labels:
  #         alias: 'lidarr'

  # - job_name: 'radarr'
  #   static_configs:
  #     - targets: ['radarr-exporter:9707']
  #       labels:
  #         alias: 'radarr'

  # - job_name: 'sonarr'
  #   static_configs:
  #     - targets: ['sonarr-exporter:9708']
  #       labels:
  #         alias: 'sonarr'

  # - job_name: 'traefik'
  #   static_configs:
  #     - targets: ['traefik:8082']
  #       labels:
  #         alias: 'traefik'

  - job_name: 'node-exporter-monitoring'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          alias: 'node'

  # - job_name: 'flaresolverr'
  #   static_configs:
  #     - targets: ['flaresolverr:8191']
  #       labels:
  #         alias: 'flaresolverr'

  - job_name: 'node-exporter-peter'
    static_configs:
      - targets: ['10.10.100.190:9100']
        labels:
          alias: 'node-exporter-peter'

  - job_name: 'graphite-exporter-proxmox'
    static_configs:
      - targets: ['graphite-exporter:9108']
        labels:
          alias: 'graphite-exporter-proxmox'

  - job_name: 'graphite-exporter-truenas'
    static_configs:
      - targets: ['graphite-exporter:9107']
        labels:
          alias: 'graphite-exporter-truenas'

  - job_name: 'unpoller'
    static_configs:
      - targets: ['unpoller:9130']
        labels:
          alias: 'unpoller'
    scrape_interval: 30s

  # - job_name: 'tdarr-exporter'
  #   static_configs:
  #     - targets: ['tdarr-exporter:9110']
  #       labels:
  #         alias: 'tdarr-exporter'

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"] # Replace IP with the hostname of the docker container if you're running the container in a separate network
# alert
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    http_headers: null
    timeout: 10s
    api_version: 'v2'
    scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
