services:
  # Bazarr Exporter - Bazarr metrics for Prometheus
  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:${EXPORTARR_TAG:-latest}
    container_name: bazarr-exporter
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["all", "exporter"]
    networks:
      - arr_net
    ports:
      - mode: ingress
        target: 9712
        published: "9712"
        protocol: tcp
    environment:
      PORT: 9712
      URL: "http://bazarr:6767"
      APIKEY: $BAZARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["bazarr"]