services:
  debian:
    image: debian:${DEBIAN_TAG:-bookworm}
    container_name: debian
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "container:gluetun"