services:
  # Dockge - Docker Compose Manager
  dockge:
    image: louislam/dockge
    container_name: dockge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    ports:
      - "5001:5001"
    networks:
      - t3_proxy
      # - socket_proxy
    volumes:
      - ${COMMON_CONFIG_PATH}/dockge:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
      # - ${COMMON_CONFIG_PATH}/test:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      # - DOCKER_HOST=tcp://socket-proxy:2375
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dockge-rtr.entrypoints=websecure"
      - "traefik.http.routers.dockge-rtr.rule=Host(`dockge.$DOMAINNAME`)"
      # Middlewares
      # - "traefik.http.routers.dockge-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.dockge-rtr.service=dockge-svc"
      - "traefik.http.services.dockge-svc.loadbalancer.server.port=5001"