services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:${FLARESOLVERR_TAG:-latest}
    container_name: flaresolverr
    restart: unless-stopped
    profiles: ["media","arrs", "all"]
    networks:
      - t3_proxy
    ports:
      - mode: ingress
        target: 8191
        published: "8191"
        protocol: tcp
    environment:
      LOG_LEVEL: ${FLARESOLVERR_LOG_LEVEL:-info}
      LOG_HTML: ${FLARESOLVERR_LOG_HTML:-false}
      CAPTCHA_SOLVER: ${FLARESOLVERR_CAPTCHA_SOLVER:-none}
      TZ: ${TZ:-Etc/UTC}
      LANG: ${LANG:-en_US.UTF-8}
      HEADLESS: ${FLARESOLVERR_HEADLESS:-true}
      BROWSER_TIMEOUT: ${FLARESOLVERR_BROWSER_TIMEOUT:-40000}
      TEST_URL: ${FLARESOLVERR_TEST_URL:-https://www.google.com}
      PORT: ${FLARESOLVERR_PORT:-8191}
      HOST: ${FLARESOLVERR_HOST:-0.0.0.0}
      PROMETHEUS_ENABLE: ${FLARESOLVERR_PROMETHEUS_ENABLE:-false}
      PROMETHEUS_PORT: ${FLARESOLVERR_PROMETHEUS_PORT:-8192}
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true