services:
  # Gluetun - VPN Client for Docker Containers and More
  gluetun:
    # Updated to previous version due to dns resolution issues with latest version
    image: qmcgaw/gluetun:${GLUETUN_TAG:-v3.39.0}
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "vpn", "all", "downloads"]
    extra_hosts:
      - "postgres:192.168.55.11"
    networks:
      - arr_net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    # healthcheck:
    #   test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
    #   interval: 5s
    #   timeout: 5s
    #   start_period: 10s
    #   retries: 1
    ports:
      # Exposing qBittorrent through Docker Host LAN IP
      - mode: ingress
        target: "${QBIT_PORT:-8080}"
        published: "${QBIT_PORT:-8080}"
        protocol: tcp
      - 6881:6881
      - 6881:6881/udp
      - mode: ingress
        target: 8000
        published: 8000
        protocol: tcp
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
      # BitMagnet API and WebUI port:
      - mode: ingress
        target: "${BITMAG_PORT:-3333}"
        published: "${BITMAG_PORT:-3333}"
        protocol: tcp
      # BitMagnet BitTorrent ports:
      - mode: ingress
        target: "${BITMAG_BT_PORT:-3334}"
        published: "${BITMAG_BT_PORT:-3334}"
        protocol: tcp
      - mode: ingress
        target: "${BITMAG_BT_PORT:-3334}"
        published: "${BITMAG_BT_PORT:-3334}"
        protocol: udp
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: gluetun_config_data
        target: /config
        bind:
          create_host_path: true
      - type: volume
        source: ./secrets/gluetun_auth_config.toml
        target: /gluetun/auth/config.toml
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-Etc/UTC}

      VPN_INTERFACE: tun0
      VPN_TYPE: ${GLUETUN_VPN_TYPE:-wireguard}
      VPN_SERVICE_PROVIDER: ${GLUETUN_VPN_PROVIDER:-nordvpn}
      WIREGUARD_PRIVATE_KEY: ${VPN_KEY}
      SERVER_COUNTRIES: ${GLUETUN_SERVER_COUNTRIES:-Netherlands}
      # STORAGE_FILEPATH: /gluetun/servers.json
      DOT: ${GLUETUN_DOT:-on}
      DOT_PROVIDERS: ${GLUETUN_DOT_PROVIDERS:-cloudflare}
      DOT_PRIVATE_ADDRESS: ${GLUETUN_DOT_PRIVATE_ADDRESS:-127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112}
      DOT_VERBOSITY: ${GLUETUN_DOT_VERBOSITY:-1}
      DOT_VERBOSITY_DETAILS: ${GLUETUN_DOT_VERBOSITY_DETAILS:-0}
      DOT_VALIDATION_LOGLEVEL: ${GLUETUN_DOT_VALIDATION_LOGLEVEL:-0}
      DOT_CACHING: ${GLUETUN_DOT_CACHING:-on}
      DOT_IPV6: ${GLUETUN_DOT_IPV6:-off}
      BLOCK_MALICIOUS: ${GLUETUN_BLOCK_MALICIOUS:-on}
      BLOCK_SURVEILLANCE: ${GLUETUN_BLOCK_SURVEILLANCE:-on}
      BLOCK_ADS: ${GLUETUN_BLOCK_ADS:-on}
      DNS_UPDATE_PERIOD: ${GLUETUN_DNS_UPDATE_PERIOD:-24h}
      DNS_ADDRESS: ${GLUETUN_DNS_ADDRESS:-127.0.0.1}
      DNS_KEEP_NAMESERVER: ${GLUETUN_DNS_KEEP_NAMESERVER:-off}
      HTTP_CONTROL_SERVER_LOG: ${GLUETUN_HTTP_CONTROL_SERVER_LOG:-on}
      HTTP_CONTROL_SERVER_ADDRESS: ${GLUETUN_HTTP_CONTROL_SERVER_ADDRESS:-":8000"}
      HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: ${GLUETUN_HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH:-/gluetun/auth/config.toml}
      UPDATER_PERIOD: ${GLUETUN_UPDATER_PERIOD:-0}
      UPDATER_MIN_RATIO: ${GLUETUN_UPDATER_MIN_RATIO:-0.8}
      PUBLICIP_FILE: ${GLUETUN_PUBLICIP_FILE:-/tmp/gluetun/ip}
      PUBLICIP_PERIOD: ${GLUETUN_PUBLICIP_PERIOD:-12h}
      PUBLICIP_API: ${GLUETUN_PUBLICIP_API:-ipinfo}
      PUBLICIP_API_TOKEN: ${GLUETUN_PUBLICIP_API_TOKEN:-}
      PPROF_ENABLED: ${GLUETUN_PPROF_ENABLED:-on}
      PPROF_BLOCK_PROFILE_RATE: ${GLUETUN_PPROF_BLOCK_PROFILE_RATE:-0}
      PPROF_MUTEX_PROFILE_RATE: ${GLUETUN_PPROF_MUTEX_PROFILE_RATE:-0}
      PPROF_HTTP_SERVER_ADDRESS: ${GLUETUN_PPROF_HTTP_SERVER_ADDRESS:-":6060"}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit-gluetun.entrypoints=web"
      - "traefik.http.routers.qbit-gluetun.rule=Host(`qbit.$DOMAINNAME`)"
      - "traefik.http.middlewares.qbit-gluetun-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qbit-gluetun.middlewares=qbit-gluetun-https-redirect"
      - "traefik.http.routers.qbit-gluetun-secure.entrypoints=websecure"
      - "traefik.http.routers.qbit-gluetun-secure.rule=Host(`qbit.$DOMAINNAME`)"
      - "traefik.http.routers.qbit-gluetun-secure.tls=true"
      - "traefik.http.routers.qbit-gluetun-secure.service=qbit-gluetun"
      - "traefik.http.services.qbit-gluetun.loadbalancer.server.scheme=https"
      - "traefik.http.services.qbit-gluetun.loadbalancer.server.port=8080"
      - "traefik.docker.network=arr_net"
volumes:
  gluetun_config_data:
    external: false
    name: gluetun_config_data