services:
  gotify:
    image: gotify/server:${GOTIFY_TAG:-latest}
    container_name: gotify
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - arr_net
    ports:
      - mode: ingress
        target: 80
        published: "${GOTIFY_PORT:-80}"
        protocol: tcp
    environment:
      GOTIFY_SERVER_PORT: 80
      GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: ${GOTIFY_SERVER_KEEPALIVEPERIODSECONDS:-0}
      GOTIFY_SERVER_LISTENADDR: ${GOTIFY_SERVER_LISTENADDR:-}
      GOTIFY_SERVER_SSL_ENABLED: ${GOTIFY_SERVER_SSL_ENABLED:-false}
      GOTIFY_SERVER_SSL_REDIRECTTOHTTPS: ${GOTIFY_SERVER_SSL_REDIRECTTOHTTPS:-true}
      GOTIFY_SERVER_SSL_LISTENADDR: ${GOTIFY_SERVER_SSL_LISTENADDR:-}
      GOTIFY_SERVER_SSL_PORT: ${GOTIFY_SERVER_SSL_PORT:-443}
      GOTIFY_SERVER_SSL_CERTFILE: ${GOTIFY_SERVER_SSL_CERTFILE:-}
      GOTIFY_SERVER_SSL_CERTKEY: ${GOTIFY_SERVER_SSL_CERTKEY:-}
      GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED: ${GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED:-false}
      GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS: ${GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS:-false}
      GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE: ${GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE:-data/certs}
      # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: [mydomain.tld, myotherdomain.tld]
      # GOTIFY_SERVER_RESPONSEHEADERS: {X-Custom-Header: "custom value", x-other: value}
      # GOTIFY_SERVER_CORS_ALLOWORIGINS: [.+\.example\.com, otherdomain\.com]
      # GOTIFY_SERVER_CORS_ALLOWMETHODS: [GET, POST]
      # GOTIFY_SERVER_CORS_ALLOWHEADERS: [X-Gotify-Key, Authorization]
      # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: [.+.example\.com, otherdomain\.com]
      GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: ${GOTIFY_SERVER_STREAM_PINGPERIODSECONDS:-45}
      GOTIFY_DATABASE_DIALECT: ${GOTIFY_DATABASE_DIALECT:-sqlite3}
      GOTIFY_DATABASE_CONNECTION: ${GOTIFY_DATABASE_CONNECTION:-data/gotify.db}
      GOTIFY_DEFAULTUSER_NAME: ${GOTIFY_DEFAULTUSER_NAME:-admin}
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS:-admin}
      GOTIFY_PASSSTRENGTH: ${GOTIFY_PASSSTRENGTH:-10}
      GOTIFY_UPLOADEDIMAGESDIR: ${GOTIFY_UPLOADEDIMAGESDIR:-data/images}
      GOTIFY_PLUGINSDIR: ${GOTIFY_PLUGINSDIR:-data/plugins}
      GOTIFY_REGISTRATION: ${GOTIFY_REGISTRATION:-false}
    volumes:
      - type: bind
        source: ${COMMON_CONFIG_PATH}/gotify
        target: /app/data
        bind:
          create_host_path: true
      # - "./gotify_data:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=web"
      - "traefik.http.routers.gotify.rule=Host(`gotify.$DOMAINNAME`)"
      - "traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.gotify.middlewares=gotify-https-redirect"
      - "traefik.http.routers.gotify-secure.entrypoints=websecure"
      - "traefik.http.routers.gotify-secure.rule=Host(`gotify.$DOMAINNAME`)"
      - "traefik.http.routers.gotify-secure.tls=true"
      - "traefik.http.routers.gotify-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.gotify-secure.service=gotify"
      # - "traefik.http.services.gotify-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "traefik.docker.network=arr_net"
