services:
  # Grafana - Graphical data visualization for InfluxDB data
  grafana:
    image: grafana/grafana-oss:${GRAFANA_TAG:-11.1.1-ubuntu}
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "exporter", "all"]
    networks:
      - t3_proxy
    ports:
      - mode: ingress
        target: 3030
        published: "3030"
        protocol: tcp
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - $DOCKERDIR/appdata/grafana:/usr/local/etc/grafana
    environment:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      # GF_PATHS_PROVISIONING: /usr/local/etc/grafana
      GF_SERVER_PROTOCOL: ${GF_SERVER_PROTOCOL:-http}
      GF_SERVER_HTTP_ADDR: ${GF_SERVER_HTTP_ADDR:-0.0.0.0}
      GF_SERVER_HTTP_PORT: ${GF_SERVER_HTTP_PORT:-3030}
      GF_SERVER_ROUTER_LOGGING: ${GF_SERVER_ROUTER_LOGGING:-true}
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE:-sqlite3}
      GF_REMOTE_CACHE_TYPE: ${GF_REMOTE_CACHE_TYPE:-database}
      GF_ANALYTICS_ENABLED: ${GF_ANALYTICS_ENABLED:-false}
      GF_ANALYTICS_REPORTING_ENABLED: ${GF_ANALYTICS_REPORTING_ENABLED:-false}
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: ${GF_ANALYTICS_FEEDBACK_LINKS_ENABLED:-false}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-password123}
      GF_SECURITY_ADMIN_EMAIL: ${GF_SECURITY_ADMIN_EMAIL:-admin@localhost}
      # GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: ${GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH:-/usr/share/grafana/public/dashboards/home.json}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP:-false}
      GF_USERS_ALLOW_ORG_CREATE: ${GF_USERS_ALLOW_ORG_CREATE:-false}
      GF_USERS_AUTO_ASSIGN_ORG: ${GF_USERS_AUTO_ASSIGN_ORG:-true}
      GF_USERS_AUTO_ASSIGN_ORG_ID: ${GF_USERS_AUTO_ASSIGN_ORG_ID:-1}
      GF_USERS_VERIFY_EMAIL_ENABLED: ${GF_USERS_VERIFY_EMAIL_ENABLED:-false}
      GF_USERS_LOGIN_DEFAULT_ORG_ID: ${GF_USERS_LOGIN_DEFAULT_ORG_ID:-1}
      GF_USERS_DEFAULT_THEME: ${GF_USERS_DEFAULT_THEME:-dark}
      GF_USERS_DEFAULT_LANGUAGE: ${GF_USERS_DEFAULT_LANGUAGE:-en-US}
      GF_AUTH_LOGIN_COOKIE_NAME: ${GF_AUTH_LOGIN_COOKIE_NAME:-grafana_session}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM:-false} # Enable for OAuth
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED:-false}
      GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP: ${GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP:-false}
      # GF_LOG_MODE: ${GF_LOG_MODE:-"file"}
      GF_LOG_LEVEL: ${GF_LOG_LEVEL:-info}
      GF_PLUGINS_ENABLE_ALPHA: ${GF_PLUGINS_ENABLE_ALPHA:-true}
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,cloudflare-app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAINNAME_HS`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.$DOMAINNAME_HS`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.grafana-secure.service=grafana"
      # - "traefik.http.services.grafana.loadbalancer.server.scheme=https"
      - "traefik.http.services.grafana.loadbalancer.server.port=3030"
      - "traefik.docker.network=t3_proxy"