services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
      # - socket_proxy
    ports:
     - "${HOMEPAGE_PORT:-3000}:3000"
    volumes:
      - ${COMMON_CONFIG_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: 0
      PGID: 0
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$DOMAINNAME_HS`) || Host(`www.$DOMAINNAME_HS`)"
      # Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"