services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/benphelps/homepage:${HOMEPAGE_TAG:-latest}
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
      # - socket_proxy
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/homepage
        target: /app/config
        bind:
          create_host_path: true
      # - ${COMMON_CONFIG_PATH}/homepage:/app/config
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.routers.homepage.rule=Host(`homepage.$DOMAINNAME_HS`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=websecure"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.$DOMAINNAME_HS`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.homepage-secure.service=homepage"
      # - "traefik.http.services.homepage-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=t3_proxy"
