services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    profiles: ["jellyfin", "all"]
    user: uid:gid
    network_mode: 'host'
    group_add:
      - 107  # Run `stat -c '%g' /dev/dri/renderD128` to get the group ID of the dri device

    devices:
      - /dev/dri:/dev/dri
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: ${COMMON_CONFIG_PATH}/jellyfin/config
      target: /config
      bind:
        create_host_path: true
    - type: bind
      source: ${COMMON_CONFIG_PATH}/jellyfin/cache
      target: /cache
      bind:
        create_host_path: true
    - type: bind
      source: ${COMMON_DATA_PATH}/movies
      target: /storage/movies
      bind:
        create_host_path: true
    - type: bind
      source: ${COMMON_DATA_PATH}/tv
      target: /storage/tv
      bind:
        create_host_path: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      # - JELLYFIN_PublishedServerUrl=http://jellyfin.$DOMAINNAME
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'