services:
  # Postgres Exporter - Postgres metrics for Prometheus
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:${POSTGRES_EXPORTER_TAG:-latest}
    container_name: postgres-exporter
    restart: "no"
    profiles: ["all", "exporter"]
    networks:
      - arr_net
    ports:
      - mode: ingress
        target: 9187
        published: "9187"
        protocol: tcp
    environment:
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
      DATA_SOURCE_URI_FILE: #The same as above but reads the URI from a file.
      # DATA_SOURCE_USER When using DATA_SOURCE_URI, this environment variable is used to specify the username.

      DATA_SOURCE_USER_FILE: The same, but reads the username from a file.

      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD:-postgres} #use with DATA_SOURCE_URI, to specify the password to connect with.

      # DATA_SOURCE_PASS_FILE The same as above but reads the password from a file.

      # PG_EXPORTER_WEB_TELEMETRY_PATH Path under which to expose metrics. Default is /metrics.

      # PG_EXPORTER_DISABLE_DEFAULT_METRICS Use only metrics supplied from queries.yaml. Value can be true or false. Default is false.

      # PG_EXPORTER_DISABLE_SETTINGS_METRICS Use the flag if you don't want to scrape pg_settings. Value can be true or false. Default is false.

      # PG_EXPORTER_EXTEND_QUERY_PATH Path to a YAML file containing custom queries to run. Check out queries.yaml for examples of the format.

      # PG_EXPORTER_METRIC_PREFIX A prefix to use for each of the default metrics exported by postgres-exporter. Default is pg