services:
  # Prometheus - Database for sensor data
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG:-v2.53.1}
    container_name: prometheus
    networks:
      - t3_proxy
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["exporter", "all"]
    ports:
      - mode: ingress
        target: 9090
        published: "9090"
        protocol: tcp
    volumes:
      - type: bind
        source: $DOCKERDIR/appdata/prometheus
        target: /etc/prometheus
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/prometheus/data
        target: /prometheus
        bind:
          create_host_path: true
      # - $DOCKERDIR/appdata/prometheus/data:/prometheus
    user: ${PUID:-1000}:${PGID:-1000}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.$DOMAINNAME_HS`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=websecure"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.$DOMAINNAME_HS`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      # - "traefik.http.services.prometheus.loadbalancer.server.scheme=https"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=t3_proxy"