services:
  # qBittorrent - Torrent downloader
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QBIT_TAG:-latest}
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      # - type: bind
      #   source: ${COMMON_CONFIG_PATH}/qbittorrent
      #   target: /config
      #   bind:
      #     create_host_path: true
      - type: volume
        source: config_data
        target: /config
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true
      # - ${COMMON_CONFIG_PATH}/qbittorrent:/config
      # - ${COMMON_DATA_PATH}/downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      WEBUI_PORT: ${QBIT_PORT:-8080}
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://ipv4.icanhazip.com/ || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels: # Traefik labels added via glueten
      - "deunhealth.restart.on.unhealthy=true"

volumes:
  config_data:
    external: false
    name: config_data