services:
  # Readarr - Book Management
  readarr:
    image: lscr.io/linuxserver/readarr:${READARR_TAG:-develop}
    container_name: readarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "arrs", "all"]
    networks:
      - arr_net
    ports:
      - mode: ingress
        target: 8787
        published: "8787"
        protocol: tcp
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/readarr
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.entrypoints=web"
      - "traefik.http.routers.readarr.rule=Host(`readarr.$DOMAINNAME`)"
      - "traefik.http.middlewares.readarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.readarr.middlewares=readarr-https-redirect"
      - "traefik.http.routers.readarr-secure.entrypoints=websecure"
      - "traefik.http.routers.readarr-secure.rule=Host(`readarr.$DOMAINNAME`)"
      - "traefik.http.routers.readarr-secure.tls=true"
      - "traefik.http.routers.readarr-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.readarr-secure.service=readarr"
      # - "traefik.http.services.readarr.loadbalancer.server.scheme=https"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - "traefik.docker.network=arr_net"