services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: lscr.io/linuxserver/socket-proxy:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      socket_proxy:
        # ipv4_address: # You can specify a static IP
    # privileged: true # true for VM. False for unprivileged LXC container.
    ports:
    #  - "$ZEROTIER_IP_CLOUDSERVER:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    # I use the next line instead, as I want portainer to manage multiple docker endpoints within my home network.
      # Do not expose this to the internet with port forwarding
      - mode: ingress
        target: 2375
        published: "2375"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
    tmpfs:
      - /run
    environment:
      ALLOW_START: ${SOCKET_PROXY_ALLOW_START:-0}
      ALLOW_STOP: ${SOCKET_PROXY_ALLOW_STOP:-0}
      ALLOW_RESTARTS: ${SOCKET_PROXY_ALLOW_RESTARTS:-0}
      AUTH: ${SOCKET_PROXY_AUTH:-0}
      BUILD: ${SOCKET_PROXY_BUILD:-0}
      COMMIT: ${SOCKET_PROXY_COMMIT:-0}
      CONFIGS: ${SOCKET_PROXY_CONFIGS:-0}
      CONTAINERS: ${SOCKET_PROXY_CONTAINERS:-1}
      DISTRIBUTION: ${SOCKET_PROXY_DISTRIBUTION:-0}
      DISABLE_IPV6: ${SOCKET_PROXY_DISABLE_IPV6:-0}
      EVENTS: ${SOCKET_PROXY_EVENTS:-1}
      EXEC: ${SOCKET_PROXY_EXEC:-0}
      IMAGES: ${SOCKET_PROXY_IMAGES:-0}
      INFO: ${SOCKET_PROXY_INFO:-0}
      NETWORKS: ${SOCKET_PROXY_NETWORKS:-0}
      NODES: ${SOCKET_PROXY_NODES:-0}
      PING: ${SOCKET_PROXY_PING:-1}
      POST: ${SOCKET_PROXY_POST:-0}
      PLUGINS: ${SOCKET_PROXY_PLUGINS:-0}
      SECRETS: ${SOCKET_PROXY_SECRETS:-0}
      SERVICES: ${SOCKET_PROXY_SERVICES:-0}
      SESSION: ${SOCKET_PROXY_SESSION:-0}
      SWARM: ${SOCKET_PROXY_SWARM:-0}
      SYSTEM: ${SOCKET_PROXY_SYSTEM:-0}
      TASKS: ${SOCKET_PROXY_TASKS:-0}
      VERSION: ${SOCKET_PROXY_VERSION:-1}
      VOLUMES: ${SOCKET_PROXY_VOLUMES:-0}

