services:
  stash:
    container_name: stash
    image: ghcr.io/hotio/stash:${STASH_TAG:-latest}
    restart: "no"
    profiles: ["media", "apps", "all"]
    networks:
      - t3_proxy

    ports:
      - mode: ingress
        target: 9999
        published: "9999"
        protocol: tcp

    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      STASH_HOST: ${STASH_HOST:-0.0.0.0}
      STASH_PORT: ${STASH_PORT:-9999}
      # STASH_EXTERNAL_HOST=stash.$DOMAINNAME
      STASH_STASH: /data/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/

    devices:
      # - /dev/fb0:/dev/fb0
      - /dev/dri:/dev/dri

    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/stash/config
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/stash/blobs
        target: /blobs
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/stash/metadata
        target: /metadata
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/stash/cache
        target: /cache
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_CONFIG_PATH}/stash/generated
        target: /generated
        bind:
          create_host_path: true
      - type: bind
        source: $DOCKERDIR/appdata/stash/add-intel-arc-drivers.sh
        target: /etc/cont-init.d/99-my-script
        bind:
          create_host_path: true

    # user: $PUID:$PGID

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stash.entrypoints=web"
      - "traefik.http.routers.stash.rule=Host(`stash.$DOMAINNAME`)"
      - "traefik.http.middlewares.stash-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.stash.middlewares=stash-https-redirect"
      - "traefik.http.routers.stash-secure.entrypoints=websecure"
      - "traefik.http.routers.stash-secure.rule=Host(`stash.$DOMAINNAME`)"
      - "traefik.http.routers.stash-secure.tls=true"
      - "traefik.http.routers.stash-secure.tls.certresolver=cloudflare-dns"
      - "traefik.http.routers.stash-secure.service=stash"
      # - "traefik.http.services.stash-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.stash.loadbalancer.server.port=9999"
      - "traefik.docker.network=t3_proxy"


      # - "traefik.enable=true"
      # # HTTP Routers Auth Bypass
      # - "traefik.http.routers.stash-rtr-bypass.entrypoints=websecure"
      # # - "traefik.http.routers.stash-rtr-bypass.rule=Host(`stash.$DOMAINNAME`) && (Header(`X-Api-Key`, `$STASH_API_KEY`) || Query(`apikey`, `$STASH_API_KEY`))"
      # - "traefik.http.routers.stash-rtr-bypass.rule=Host(`stash.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      # - "traefik.http.routers.stash-rtr-bypass.priority=100"
      # # HTTP Routers Auth
      # - "traefik.http.routers.stash-rtr.entrypoints=websecure"
      # - "traefik.http.routers.stash-rtr.rule=Host(`stash.$DOMAINNAME`)"
      # - "traefik.http.routers.stash-rtr.priority=99"
      # # Middlewares
      # - "traefik.http.routers.stash-rtr-bypass.middlewares=chain-no-auth@file"
      # # - "traefik.http.routers.stash-rtr.middlewares=chain-oauth@file"
      # # HTTP Services
      # - "traefik.http.routers.stash-rtr.service=stash-svc"
      # - "traefik.http.routers.stash-rtr-bypass.service=stash-svc"
      # - "traefik.http.services.stash-svc.loadbalancer.server.port=9999"