# Do we need or want UMASK_SET=002 in environment?
services:
  tdarr-server:
    container_name: tdarr-server
    image: ghcr.io/haveagitgat/tdarr:${TDARR_SERVER_TAG:-latest}
    restart: unless-stopped
    profiles: ["media", "tdarrserver", "tdarr", "all"]
    network_mode: bridge
    ports:
      - mode: ingress
        target: 8265
        published: 8265
        protocol: tcp
      - mode: ingress
        target: 8266
        published: 8266
        protocol: tcp

    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: 1000
      PGID: 1000
      # PUID: ${PUID:-1000}
      # PGID: ${PGID:-1000}
      serverIP: ${TDARR_SERVER_IP:-0.0.0.0}
      serverPort: ${TDARR_SERVER_PORT:-8266}
      webUIPort: ${TDARR_UI_PORT:-8265}
      internalNode: true
      inContainer: true
      ffmpegVersion: 7
      nodeName: ${TDARR_SERVER_NAME:-MyInternalNode}

    group_add:
      - 106

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - type: volume
        source: tdarr_server_data
        target: /app/server
      - type: volume
        source: tdarr_configs
        target: /app/configs
      - type: volume
        source: tdarr_logs
        target: /app/logs
      - type: bind
        source: ${COMMON_CONFIG_PATH}/cache
        target: /cache
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true

volumes:
  tdarr_server_data:
    external: false
    name: tdarr_server_data
  tdarr_configs:
    external: false
    name: tdarr_configs
  tdarr_logs:
    external: false
    name: tdarr_logs
