services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:${TDARR_NODE_TAG:-latest}
    restart: unless-stopped
    profiles: ["media", "all", "tdarr", "tdarrnode"]
    network_mode: service:tdarr-server
    user: "106:106"
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: 1000
      PGID: 1000
      serverIP: ${TDARR_SERVER_IP:-0.0.0.0}
      serverPort: ${TDARR_SERVER_PORT:-8266}
      inContainer: true
      ffmpegVersion: 7
      nodeName: ${TDARR_NODE_NAME:-MyExternalNode}

    # group_add:
    #   - 106

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - type: volume
        source: tdarr_configs
        target: /app/configs
      - type: volume
        source: tdarr_logs
        target: /app/logs
      - type: bind
        source: ${COMMON_CONFIG_PATH}/cache
        target: /cache
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true

volumes:
  tdarr_configs:
    external: false
    name: tdarr_configs
  tdarr_logs:
    external: false
    name: tdarr_logs
