services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:${TDARR_NODE_TAG:-latest}
    restart: unless-stopped
    profiles: ["media", "all", "tdarrnode"]
    networks:
      - t3_proxy
    # ports:
    #   - mode: ingress
    #     target: 8268
    #     published: 8268
    #     protocol: tcp
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      serverIP: ${TDARR_SERVER_IP:-0.0.0.0}
      serverPort: ${TDARR_SERVER_PORT:-8266}
      inContainer: true
      ffmpegVersion: 6
      nodeName: ${TDARR_NODE_NAME:-MyExternalNode}

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - type: volume
        source: tdarr_configs
        target: /app/configs
      - type: volume
        source: tdarr_logs
        target: /app/logs
      - type: bind
        source: ${COMMON_CONFIG_PATH}/cache
        target: /cache
        bind:
          create_host_path: true
      - type: bind
        source: ${COMMON_DATA_PATH}
        target: /storage
        bind:
          create_host_path: true

volumes:
  tdarr_configs:
    external: false
    name: tdarr_configs
  tdarr_logs:
    external: false
    name: tdarr_logs
  # transcode_cache:
  #   external: false
  #   name: transcode_cache
