services:
  # Whisparr Exporter - Whisparr metrics for Prometheus
  whisparr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: whisparr-exporter
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["all", "exporter"]
    networks:
      - arr_net
    ports:
      - mode: ingress
        target: 9711
        published: "9711"
        protocol: tcp
    environment:
      PORT: 9711
      URL: "http://whisparr:6969"
      APIKEY: $WHISPARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["whisparr"]