---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-techcasa-io
  namespace: cattle-system
spec:
  commonName: rancher.techcasa.io
  secretName: rancher-cert
  dnsNames:
    - rancher.techcasa-io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
