---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  namespace: rancher
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.techcasa.io`) # change with your value
      kind: Rule
      services:
        - name: rancher
          port: 80
        - name: rancher
          port: 443
  tls:
    secretName: rancher-cert # change this to your secret!!!