---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  namespace: cattle-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`rancher.techcasa.io`) # change with your value
      kind: Rule
      services:
        - name: rancher
          port: 80
  tls:
    secretName: techcasa-tls # change this to your secret!!!