---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  annotations:
    kubernetes.io/ingress.class: traefik-external # change with your value
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.techcasa.io`) # change with your value
      kind: Rule
      services:
        - name: rancher
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secretName: techcasa-tls # change this to your secret!!!