---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.techcasa.io`) # change with your value
      kind: Rule
  tls:
    secretName: techcasa-io-production-tls # change this to your secret!!!