---
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:${NETBOOT_TAG:-latest}
    container_name: netbootxyz
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
      PORT_RANGE: 30000:30010 #optional
      SUBFOLDER: / #optional
      NGINX_PORT: 80 #optional
      WEB_APP_PORT: 3000 #optional
      # - MENU_VERSION=1.9.9 #optional
    volumes:
      - type: bind
        source: /etc/netbootxyz
        target: /config
      - type: bind
        source: /mnt/iso/template/iso
        target: /assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
