services:
  czkawka:
    image: jlesage/czkawka
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - UMASK=022
      - LANG=en_US.UTF-8
      - TZ=${TZ:-Etc/UTC}
      - KEEP_APP_RUNNING=1
      # - APP_NICENESS=-20
      - CONTAINER_DEBUG=0
      - DARK_MODE=1
      - SECURE_CONNECTION=1
      # - WEB_AUTHENTICATION=1
      # - WEB_AUTHENTICATION_USERNAME=${USERNAME:-admin}
      # - WEB_AUTHENTICATION_PASSWORD=${PASSWORD:-password}
      - WEB_LISTENING_PORT=5800
      - VNC_LISTENING_PORT=5900
      - VNC_PASSWORD=${VNC_PASSWORD:-password}
    volumes:
      - config_data:/config:rw
      - /mnt/rclark:/storage:rw

volumes:
  config_data:
    external: false
    name: config_data
